#%RAML 1.0
title: AMQ migration App
mediaType: [application/json]

types:
  queueMigrationDetails: !include dataTypes/queueMigrationDetails.raml
  
    
  
traits:
  commonHeaders: !include traits/commonHeaders.raml
  

/migrate/queue:
  post:
    is: [commonHeaders]
    body:
      application/json:
        type: queueMigrationDetails
    responses:
      202:
        body:
          application/json:


            
            

