#%RAML 1.0
title: hybrid-bulk-deploy
mediaType: [application/json]

types:
  appDetails: !include dataTypes/appDetailsType.raml
  rftMigrationDetails: !include dataTypes/rtfMigrationDetails.raml
  queueMigrationDetails: !include dataTypes/queueMigrationDetails.raml
  alertType: !include dataTypes/alertType.raml
  
    
  
traits:
  commonHeaders: !include traits/commonHeaders.raml
  

/migrate/queue:
  post:
    is: [commonHeaders]
    body:
      application/json:
        type: queueMigrationDetails
    responses:
      202:
        body:
          application/json:


            
            

